load('ext://deployment', 'deployment_create')
load('ext://configmap', 'configmap_create')
# This gets the directory where the extension is located locally
home = os.getcwd()

def config_server_deployment(kubernetesConfigServerYamlPath):
    objects=['spring-cloud-kubernetes-configserver:ServiceAccount', 'spring-cloud-kubernetes-configserver\\:view:RoleBinding', 'namespace-reader:Role']
    if kubernetesConfigServerYamlPath:
    	configmap_create('kubernetesconfigserver', from_file=['application.yaml=' + kubernetesConfigServerYamlPath])
    	objects.append('kubernetesconfigserver:ConfigMap')

	k8s_yaml(os.path.join(home, 'configserver.yaml'))
	k8s_resource('spring-cloud-kubernetes-configserver-deployment', port_forwards=['8888:8888'], objects=objects)

