def modify_deployment_for_livereload(deployment):
	container = deployment['spec']['template']['spec']['containers'][0]
	container['securityContext'].clear()
	container['securityContext']['runAsUser'] = 1001

def modify_jkube_kubernetes_yaml_for_livereload(kube_yaml_path):
	return modify_jkube_kubernetes_yaml_for_livereload_blob(local(kube_yaml_path))

def modify_jkube_kubernetes_yaml_for_livereload_blob(kube_yaml_blob):
	resources = decode_yaml_stream(str(kube_yaml_blob))
	items = resources.pop()['items']
	deployment = items.pop()
	modify_deployment_for_livereload(deployment)
	items.append(deployment)
	resources.append({"apiVersion": "v1", "items": items, "kind": "List"})
	return encode_yaml_stream(resources)
