def discovery_server_deployment():
        print(os.getcwd())
	objects=['spring-cloud-kubernetes-discoveryserver:ServiceAccount', 'spring-cloud-kubernetes-discoveryserver\\:view:RoleBinding', 'namespace-reader-discoveryserver:Role']
	k8s_yaml('k8s/spring-cloud-k8s/discoveryserver/discoveryserver.yaml')
	k8s_resource('spring-cloud-kubernetes-discoveryserver-deployment', port_forwards=['8761:8761'], objects=objects)

