v1alpha1.extension(name='live-reload', repo_name='tilt-extensions', repo_path='live-reload')
v1alpha1.extension(name='spring-cloud-k8s-configserver', repo_name='tilt-extensions', repo_path='spring-cloud-k8s-configserver')
v1alpha1.extension(name='spring-cloud-k8s-discoveryserver', repo_name='tilt-extensions', repo_path='spring-cloud-k8s-discoveryserver')
v1alpha1.extension(name='mysql', repo_name='tilt-extensions', repo_path='mysql')
jkube = load_dynamic('ext://live-reload')
configserver = load_dynamic('ext://spring-cloud-k8s-configserver')
discoveryserver = load_dynamic('ext://spring-cloud-k8s-discoveryserver')
mysql = load_dynamic('ext://mysql')
configmap = load_dynamic('ext://configmap')

def configmap_create(name, namespace="", from_file=None, watch=True, from_env_file=None):
	configmap = load_dynamic('ext://configmap')
	return configmap.configmap_create(name, namespace, from_file, watch, from_env_file)

def configmap_from_dict(name, namespace="", inputs={}):
	configmap = load_dynamic('ext://configmap')
	return configmap.configmap_from_dict(name, namespace, inputs)
