v1alpha1.extension(name='live-reload', repo_name='tilt-extensions', repo_path='live-reload')
v1alpha1.extension(name='spring-cloud-k8s-configserver', repo_name='tilt-extensions', repo_path='spring-cloud-k8s-configserver')
v1alpha1.extension(name='spring-cloud-k8s-discoveryserver', repo_name='tilt-extensions', repo_path='spring-cloud-k8s-discoveryserver')
v1alpha1.extension(name='mysql', repo_name='tilt-extensions', repo_path='mysql')
load('ext://live-reload', 'modify_jkube_kubernetes_yaml_for_livereload')
load('ext://spring-cloud-k8s-configserver', 'config_server_deployment')
load('ext://spring-cloud-k8s-discoveryserver', 'discovery_server_deployment')
load('ext://mysql', 'add_service_binding')
load('ext://mysql', 'create_mysql_resource')

def all_extensions():
    load('ext://mysql', 'add_service_binding')
    load('ext://mysql', 'create_mysql_resource')
	return
